SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE WHERE SUBSTR(EMP_NO,8,1) IN('1','3');
SELECT * FROM (SELECT e.*, decode(substr(emp_no,8,1),'1','M','2','F','3','M','4','F')AS GENDER FROM EMPLOYEE e) WHERE GENDER='F';

SELECT * FROM SALGRADE;
SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_CODE=D.DEPT_ID;
SELECT * FROM JOB;