SELECT * FROM BOARD;
SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_COMMENT_NO;
SELECT * FROM BOARD_COMMENT;
SELECT * FROM MEMBER;

SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF JOIN MEMBER ON BOARD_WRITER=USERID WHERE BOARD_NO ='31';
SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF WHERE BOARD_NO ='31';
SELECT * FROM BOARD WHERE BOARD_NO='31';

SELECT * FROM BOARD 
	LEFT JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF 
	JOIN MEMBER ON BOARD_WRITER=USERID 
	JOIN MEMBER M ON BOARD_COMMENT_WRITER=M.USERID
WHERE BOARD_NO = '31';